services:
  web:
    container_name: 'blog'
    hostname: 'blog'
    build:
      context: ../workspace
      dockerfile: ../.devcontainer/Dockerfile
    working_dir: '/workspace'
    tty: true
    stdin_open: true
    user: "node"
    command: ["sh", "-c", "while true; do sleep 30; done"]
    mem_limit: 4g
    security_opt:
      - seccomp:unconfined
    ports:
      - 3000:3000
      - 5173:5173
      - 8080:8080
    volumes:
      - type: bind
        source: ../workspace
        target: /workspace
    environment:
      - NODE_ENV=development